name: "[EN-F] Refactor / Technical Improvement"
description: "[EN-F] Code restructuring or cleanup without changing external behavior"
title: "[Refactor] "
labels: ["refactor"]

body:
  - type: markdown
    attributes:
      value: |
        Propose code restructuring or technical improvements that do NOT change external behavior.
        If the change affects functionality or specifications, please use the Feature / Enhancement form instead.

  - type: textarea
    id: target
    attributes:
      label: Target Area
      description: Which file, module, or component is affected?
      placeholder: |
        Example:
        - src/api/user.rs
        - frontend/components/LoginForm.tsx
        - Authentication logic
      render: markdown
    validations:
      required: true

  - type: textarea
    id: current_problem
    attributes:
      label: Current Problem
      description: Why is this refactor necessary?
      placeholder: |
        Example:
        - Low readability
        - Too much duplicated code
        - Responsibilities are not clearly separated
        - Difficult to test
      render: markdown
    validations:
      required: true

  - type: textarea
    id: improvement_plan
    attributes:
      label: Improvement Plan
      description: How do you plan to improve it?
      placeholder: |
        Example:
        - Split large functions into smaller ones
        - Extract shared logic into utilities
        - Redesign type structures
      render: markdown
    validations:
      required: true

  - type: checkboxes
    id: goals
    attributes:
      label: Goals
      options:
        - label: Improve readability
        - label: Improve maintainability
        - label: Improve performance
        - label: Strengthen security
        - label: Improve testability
        - label: Reduce technical debt
      required: false

  - type: checkboxes
    id: affected_area
    attributes:
      label: Affected Areas
      options:
        - label: Frontend
        - label: Backend
        - label: Database
        - label: Infrastructure
        - label: CI / Build
        - label: Documentation
      required: false

  - type: textarea
    id: risk
    attributes:
      label: Risks / Considerations
      description: Are there any potential side effects?
      placeholder: |
        Example:
        - Test cases may need updates
        - Internal response structure could change
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: This change does NOT modify external behavior (API / UI).
          required: true
        - label: I have checked existing issues.
          required: true