name: "[JP-F] 機能要望"
description: "[JP-F] 新機能・改善提案用の日本語フォーム"
title: "[Feature] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        新機能の提案や既存機能の改善案を記入してください。

  - type: textarea
    id: background
    attributes:
      label: 背景 / 解決したい課題
      description: どのような課題がありますか？なぜこの機能が必要ですか？
      placeholder: |
        例:
        - 現在〇〇が手動でしかできない
        - APIに△△エンドポイントがなく不便
        - UIが直感的でない
      render: markdown
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
      description: どのような機能・改善を提案しますか？
      placeholder: |
        例:
        - 新しいAPIエンドポイントを追加
        - 設定画面にトグルを追加
        - CLIに--dry-runオプションを追加
      render: markdown
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる方法があれば記載してください。
      placeholder: |
        例:
        - 別モジュールとして提供する
        - 既存機能を拡張する形で実装する
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: affected_area
    attributes:
      label: 想定される影響範囲
      options:
        - label: Frontend
        - label: Backend
        - label: Database
        - label: Infrastructure
        - label: Documentation
        - label: CI / Build
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 優先度（提案者視点）
      description: どの程度優先すべきだと考えますか？
      options:
        - High / 高（早めに必要）
        - Medium / 中（余裕があれば）
        - Low / 低（将来的に）
      default: 1
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 補足情報
      description: 参考リンクや関連Issueなど
      placeholder: |
        例:
        - Related to #123
        - 参考資料URL
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: 確認事項
      options:
        - label: 既存のIssueを確認しました。
          required: true